using System;
using System.Collections.Generic;
using UnityEngine;

namespace TonyMods
{
    // Original low-poly M4A1 from M4/Assets/model.json (generated by M4/tools/create-m4-model.js).
    // Replaces the native musket mesh on first-person, third-person and dropped-item prefabs.
    internal sealed class M4Model : MonoBehaviour
    {
        [Serializable] public sealed class Definition { public Bone[] bones; public Piece[] parts; }
        [Serializable] public sealed class Bone { public string name, parent; public float[] p; }
        [Serializable] public sealed class Piece { public string name, bone, role; public float[] p, s, r, color, vertices; public int[] triangles; }

        public const string NativeMesh = "Musket1_2_1";
        // Musket mesh space: barrel along -X, butt at +0.419, bore near +0.03. Metres -> mesh units.
        private const float ButtX = .419f, BoreY = .03f, ModelButt = .256f, ModelBore = .02f;
        private static readonly Color FdeFurniture = new Color(.6f, .51f, .36f), FdeMag = new Color(.56f, .48f, .34f);
        private static Definition definition;
        private static Mesh[] meshes;
        private static Mesh flashMesh;
        private static Material metal, polymer, glow, flashMaterial;

        public Transform Recoil { get; private set; }
        public Transform Muzzle { get; private set; }
        public Transform Port { get; private set; }
        private readonly Dictionary<string, Transform> bones = new Dictionary<string, Transform>();
        private readonly Dictionary<string, Vector3> rest = new Dictionary<string, Vector3>();
        private readonly List<KeyValuePair<Renderer, Piece>> renderers = new List<KeyValuePair<Renderer, Piece>>();
        private Renderer native;
        private GameObject flash;
        private Light flashLight;
        private float flashUntil;

        public Transform Joint(string name) { Transform t; return bones.TryGetValue(name, out t) ? t : null; }
        public Vector3 Rest(string name) { Vector3 v; return rest.TryGetValue(name, out v) ? v : Vector3.zero; }

        public static bool IsSkinned(Transform root) { return root != null && root.GetComponentInChildren<M4Model>(true) != null; }

        // Returns null when the prefab no longer carries the native musket mesh.
        public static M4Model Skin(Transform root, bool firstPerson, float scale, Vector3 offset, bool fde)
        {
            if (root == null) return null;
            M4Model existing = root.GetComponentInChildren<M4Model>(true);
            if (existing != null) return existing;
            Transform mesh = Find(root, NativeMesh);
            if (mesh == null) return null;
            return Attach(mesh, firstPerson, scale, offset, fde);
        }

        private static Transform Find(Transform root, string name)
        {
            if (root.name == name) return root;
            for (int i = 0; i < root.childCount; i++) { Transform hit = Find(root.GetChild(i), name); if (hit != null) return hit; }
            return null;
        }

        private static M4Model Attach(Transform mesh, bool firstPerson, float scale, Vector3 offset, bool fde)
        {
            EnsureShared();
            GameObject holder = new GameObject("Tony M4");
            holder.layer = mesh.gameObject.layer;
            holder.transform.SetParent(mesh.parent, false);
            holder.transform.localPosition = mesh.localPosition;
            holder.transform.localRotation = mesh.localRotation;
            holder.transform.localScale = mesh.localScale;
            M4Model model = holder.AddComponent<M4Model>();
            try { model.Build(mesh, firstPerson, scale, offset, fde); }
            catch { Destroy(holder); throw; }
            return model;
        }

        private void Build(Transform mesh, bool firstPerson, float scale, Vector3 offset, bool fde)
        {
            Transform mapping = Node("Mapping", transform);
            mapping.localPosition = new Vector3(ButtX - ModelButt * scale, BoreY - ModelBore * scale, 0) + offset;
            mapping.localRotation = Quaternion.Euler(0, -90, 0);
            mapping.localScale = Vector3.one * scale;
            Recoil = Node("Recoil", mapping);
            foreach (Bone b in definition.bones)
            {
                Transform node = Node(b.name, String.IsNullOrEmpty(b.parent) ? Recoil : bones[b.parent]);
                node.localPosition = V(b.p); bones.Add(b.name, node); rest.Add(b.name, node.localPosition);
            }
            for (int i = 0; i < definition.parts.Length; i++)
            {
                Piece p = definition.parts[i];
                GameObject go = new GameObject(p.name); go.layer = gameObject.layer;
                go.transform.SetParent(bones[p.bone], false);
                go.transform.localPosition = V(p.p); go.transform.localScale = V(p.s); go.transform.localRotation = Quaternion.Euler(V(p.r));
                go.AddComponent<MeshFilter>().sharedMesh = meshes[i];
                MeshRenderer renderer = go.AddComponent<MeshRenderer>();
                renderer.sharedMaterial = p.name == "Fiber optic" ? glow : IsPolymer(p) ? polymer : metal;
                renderer.shadowCastingMode = firstPerson ? UnityEngine.Rendering.ShadowCastingMode.Off : UnityEngine.Rendering.ShadowCastingMode.On;
                renderer.receiveShadows = !firstPerson;
                renderers.Add(new KeyValuePair<Renderer, Piece>(renderer, p));
            }
            Muzzle = Node("Muzzle", bones["rifle"]); Muzzle.localPosition = new Vector3(0, ModelBore, .612f);
            Port = Node("Ejection port", bones["rifle"]); Port.localPosition = new Vector3(.024f, .018f, .1f);
            BuildFlash();
            SetColorway(fde);
            native = mesh.GetComponent<Renderer>();
            if (native != null) native.enabled = false;
        }

        private Transform Node(string name, Transform parent)
        {
            GameObject go = new GameObject(name); go.layer = gameObject.layer;
            go.transform.SetParent(parent, false); return go.transform;
        }

        private static bool IsPolymer(Piece p) { return p.role == "furniture" || p.role == "mag" || p.name == "Butt pad" || p.name == "Eye guard"; }
        private static Vector3 V(float[] v) { return v == null || v.Length < 3 ? Vector3.zero : new Vector3(v[0], v[1], v[2]); }

        public void SetColorway(bool fde)
        {
            var block = new MaterialPropertyBlock();
            foreach (var pair in renderers)
            {
                Piece p = pair.Value;
                Color color = fde && p.role == "furniture" ? FdeFurniture : fde && p.role == "mag" ? FdeMag : new Color(p.color[0], p.color[1], p.color[2]);
                block.SetColor("_BaseColor", color); block.SetColor("_Color", color);
                pair.Key.SetPropertyBlock(block);
            }
        }

        private void BuildFlash()
        {
            flash = new GameObject("Muzzle flash"); flash.layer = gameObject.layer;
            flash.transform.SetParent(Muzzle, false);
            flash.AddComponent<MeshFilter>().sharedMesh = flashMesh;
            MeshRenderer renderer = flash.AddComponent<MeshRenderer>();
            renderer.sharedMaterial = flashMaterial; renderer.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            GameObject light = new GameObject("Muzzle light"); light.transform.SetParent(Muzzle, false);
            light.transform.localPosition = new Vector3(0, 0, .05f);
            flashLight = light.AddComponent<Light>();
            flashLight.type = LightType.Point; flashLight.range = 5; flashLight.intensity = 2.2f; flashLight.color = new Color(1, .74f, .4f);
            flashLight.shadows = LightShadows.None;
            flash.SetActive(false); flashLight.enabled = false;
        }

        public void Flash()
        {
            if (flash == null) return;
            flashUntil = Time.time + .04f;
            flash.transform.localRotation = Quaternion.Euler(0, 0, UnityEngine.Random.Range(0f, 360f));
            flash.transform.localScale = Vector3.one * UnityEngine.Random.Range(.8f, 1.2f);
            flash.SetActive(true); flashLight.enabled = true;
        }

        private void Update()
        {
            if (flash != null && flash.activeSelf && Time.time >= flashUntil) { flash.SetActive(false); flashLight.enabled = false; }
        }

        private void OnDestroy()
        {
            // The holder can die before the native prefab (mod shutdown): give the musket mesh back.
            if (native != null) native.enabled = true;
        }

        private static void EnsureShared()
        {
            if (definition != null) return;
            Definition data;
            using (var stream = typeof(M4Model).Assembly.GetManifestResourceStream("Tony.M4.model.json"))
            {
                if (stream == null) throw new InvalidOperationException("M4 model resource missing");
                using (var reader = new System.IO.StreamReader(stream)) data = Newtonsoft.Json.JsonConvert.DeserializeObject<Definition>(reader.ReadToEnd());
            }
            if (data == null || data.bones == null || data.parts == null) throw new InvalidOperationException("M4 model resource invalid");
            Shader lit = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
            if (lit == null) throw new InvalidOperationException("M4 shader unavailable");
            var built = new Mesh[data.parts.Length];
            for (int i = 0; i < built.Length; i++) built[i] = AuthoredMesh(data.parts[i]);
            metal = Surface(lit, "Tony M4 metal", .45f, .5f);
            polymer = Surface(lit, "Tony M4 polymer", 0, .22f);
            glow = Surface(lit, "Tony M4 fiber", 0, .6f);
            glow.EnableKeyword("_EMISSION"); glow.SetColor("_EmissionColor", new Color(.25f, .9f, .3f) * 1.6f);
            Shader unlit = Shader.Find("Universal Render Pipeline/Unlit") ?? lit;
            flashMaterial = new Material(unlit); flashMaterial.name = "Tony M4 flash"; flashMaterial.hideFlags = HideFlags.DontUnloadUnusedAsset;
            Color hot = new Color(1, .82f, .45f);
            flashMaterial.color = hot;
            if (flashMaterial.HasProperty("_BaseColor")) flashMaterial.SetColor("_BaseColor", hot);
            if (unlit == lit) { flashMaterial.EnableKeyword("_EMISSION"); flashMaterial.SetColor("_EmissionColor", hot * 3); }
            flashMesh = BuildFlashMesh();
            meshes = built; definition = data;
        }

        private static Material Surface(Shader shader, string name, float metallic, float smoothness)
        {
            Material m = new Material(shader); m.name = name; m.hideFlags = HideFlags.DontUnloadUnusedAsset;
            if (m.HasProperty("_Metallic")) m.SetFloat("_Metallic", metallic);
            if (m.HasProperty("_Smoothness")) m.SetFloat("_Smoothness", smoothness);
            return m;
        }

        // Faceted: every triangle gets its own corners, matching the horse pipeline and the preview.
        private static Mesh AuthoredMesh(Piece p)
        {
            if (p.vertices == null || p.vertices.Length % 3 != 0 || p.triangles == null || p.triangles.Length % 3 != 0 || p.color == null || p.color.Length < 3)
                throw new InvalidOperationException("Invalid M4 geometry: " + p.name);
            int count = p.vertices.Length / 3;
            var corners = new Vector3[p.triangles.Length];
            var indices = new int[corners.Length];
            for (int i = 0; i < corners.Length; i++)
            {
                int v = p.triangles[i];
                if (v < 0 || v >= count) throw new InvalidOperationException("M4 triangle index out of range: " + p.name);
                corners[i] = new Vector3(p.vertices[v * 3], p.vertices[v * 3 + 1], p.vertices[v * 3 + 2]); indices[i] = i;
            }
            Mesh mesh = new Mesh(); mesh.name = "Tony M4 " + p.name; mesh.hideFlags = HideFlags.DontUnloadUnusedAsset;
            mesh.vertices = corners; mesh.triangles = indices;
            mesh.RecalculateNormals(); mesh.RecalculateBounds(); return mesh;
        }

        // Three crossed four-point stars along the barrel axis (+Z), double-sided.
        private static Mesh BuildFlashMesh()
        {
            var vertices = new List<Vector3>(); var triangles = new List<int>();
            for (int k = 0; k < 3; k++)
            {
                Quaternion q = Quaternion.Euler(0, 0, k * 60);
                Vector3 a = q * new Vector3(0, 0, -.005f), b = q * new Vector3(.028f, 0, .03f), c = q * new Vector3(0, 0, .11f), d = q * new Vector3(-.028f, 0, .03f);
                int o = vertices.Count; vertices.Add(a); vertices.Add(b); vertices.Add(c); vertices.Add(d);
                triangles.AddRange(new[] { o, o + 1, o + 2, o, o + 2, o + 3, o, o + 2, o + 1, o, o + 3, o + 2 });
            }
            Mesh mesh = new Mesh(); mesh.name = "Tony M4 flash"; mesh.hideFlags = HideFlags.DontUnloadUnusedAsset;
            mesh.SetVertices(vertices); mesh.SetTriangles(triangles, 0); mesh.RecalculateNormals(); mesh.RecalculateBounds();
            return mesh;
        }

        public static void ReleaseShared()
        {
            if (meshes != null) foreach (Mesh m in meshes) if (m != null) Destroy(m);
            foreach (UnityEngine.Object o in new UnityEngine.Object[] { flashMesh, metal, polymer, glow, flashMaterial }) if (o != null) Destroy(o);
            meshes = null; definition = null; flashMesh = null; metal = polymer = glow = flashMaterial = null;
        }
    }
}
